config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :quotes do
    collection do
      get :paginate
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
# frozen_string_literal: true

class Quote < ApplicationRecord
  include PgSearch::Model

  MAX_QUOTE_LENGTH = 255
  ORDER_TYPES = {
    'A-Z': { text: :asc },
    'Z-A': { text: :desc },
    Newest: { created_at: :asc },
    Oldest: { created_at: :desc }
  }.freeze

  validates :text, presence: true, length: { maximum: MAX_QUOTE_LENGTH }

  pg_search_scope :search_by_text, against: :text, using: :tsearch
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
# frozen_string_literal: true

class QuotesController < ApplicationController
  include Pagy::Backend
  include GenericResponsesHelper

  before_action :find_quote, only: %i[update edit destroy show]
  before_action :find_quotes, only: %i[index paginate]

  def index; end

  def paginate; end

  def show; end

  def new; end

  def edit; end

  def create
    @quote = Quote.create(quote_params)
    return if @quote.invalid?

    redirect_back_or_to(quotes_path)
  end

  def update
    @quote.update(quote_params)
  end

  def destroy
    @quote.destroy!
    from?(:show) ? redirect_to(quotes_path) : redirect_back_or_to(quotes_path)
  end

  private

  def find_quote
    @quote = Quote.find(params[:id])
  end

  def find_quotes
    query = quotes_params[:query]
    order = Quote::ORDER_TYPES.fetch(quotes_params[:order].to_s.to_sym, Quote::ORDER_TYPES[:'A-Z'])
    @quotes = Quote.order(**order)
    @quotes = @quotes.search_by_text(query) if query.present?
    @pagy, @quotes = pagy(@quotes)
  end

  def quotes_params
    params.permit(:page, :query, :order)
  end

  def quote_params
    params.require(:quote).permit(:text)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/generic_responses_helper.rb
module GenericResponsesHelper
  def from?(action)
    params[:from].to_s.to_sym == action
  end
end

app/helpers/pagy_helper.rb
# frozen_string_literal: true

module PagyHelper
  include Pagy::Frontend

  PAGINATE_ROUTE = 'paginate'
  PAGINATE_REGEX = %r{/#{PAGINATE_ROUTE}\??}

  def pagy_url_for(pagy, page, absolute: false, html_escaped: false, separate_route: false)
    url = super(pagy, page, absolute:, html_escaped:)
    return url if !separate_route || url.match?(PAGINATE_REGEX)

    path, query_params = url.split('?', 2)
    "#{path}/#{PAGINATE_ROUTE}?#{query_params}"
  end

  def pagy_next_link(pagy, text: pagy_t('pagy.nav.next'), link_extra: '', separate_route: false)
    if pagy.next
      %(<span class="page next"><a href="#{
          pagy_url_for(pagy, pagy.next, html_escaped: true, separate_route:)
        }" rel="next" aria-label="next" #{
          pagy.vars[:link_extra]
        } #{link_extra}>#{text}</a></span>)
    else
      %(<span class="page next disabled">#{text}</span>)
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title StimulusTurboDemo
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body.h-screen
    = yield

app/views/quotes/create.turbo_stream.haml
= turbo_stream.replace :new_quote do
  = render partial: 'quotes/partials/form', locals: { quote: @quote }

app/views/quotes/destroy.turbo_stream.haml
= turbo_stream.remove "#{dom_id(@quote)}_container"

app/views/quotes/edit.html.haml
%main
  = turbo_frame_tag dom_id(@quote) do
    = render partial: 'quotes/partials/form', locals: { quote: @quote }

app/views/quotes/index.html.haml
%main
  .flex.flex-col.items-center
    %h1.text-2xl.mb-3.mt-6 Quotes
    .mt-3.py-3{ class: 'w-6/12' }
      = render partial: 'quotes/partials/filtering'
    .flex.py-3.items-center{ class: 'w-6/12' }
      %div{ class: 'flex-[4]'}
        = render partial: 'quotes/partials/form', locals: { quote: Quote.new }
    .bg-white{ class: 'h-0.5 w-9/12' }
  = turbo_frame_tag :quotes, class: 'flex flex-col items-stretch overflow-y-scroll mt-3 mx-auto h-[68vh] w-10/12' do
    = render partial: 'quotes/partials/quote', collection: @quotes
    = render partial: 'quotes/partials/pagy', locals: { pagy: @pagy }

app/views/quotes/paginate.turbo_stream.haml
= turbo_stream.remove :pagy 
= turbo_stream.append :quotes do
  = render partial: 'quotes/partials/quote', collection: @quotes
  = render partial: 'quotes/partials/pagy', locals: { pagy: @pagy }

app/views/quotes/partials/_filtering.html.haml
.flex.items-center
  %span.mr-2 Search:
  = form_with url: quotes_path, method: :get, class: 'flex', data: { 'turbo_frame': :quotes, 'turbo-action': :replace, controller: :search, 'search-target': :form } do |form|
    = form.text_field :query, value: params[:query], data: { action: 'search#search' }, class: 'border rounded border-white border-2 w-full p-1 mr-2'
    = form.select :order, Quote::ORDER_TYPES.keys, { selected: params[:order] }, data: { action: 'search#submitForm' }, class: 'border rounded border-white border-2 hover:bg-white hover:text-black p-1'

app/views/quotes/partials/_form.html.haml
= form_with model: quote, id: dom_id(quote), class: 'flex flex-col' do |form|
  .flex
    = form.text_area :text, class: 'border rounded border-white border-2 w-full mr-3 p-1'
    - if quote.persisted?
      .flex.flex-col.h-full
        = link_to 'Cancel', :back, data: { 'turbo-frame': dom_id(quote) }, class: 'h-full text-center w-20 border rounded border-white border-2 p-1 hover:bg-white hover:text-black'
        = form.button 'Update', type: :submit, class: 'w-20 h-full mt-1 border rounded border-white border-2 p-1 hover:bg-white hover:text-black'
    - else
      = form.button 'Create', type: :submit, class: 'w-20 border rounded border-white border-2 p-1 hover:bg-white hover:text-black'
  - if quote.errors.any?
    %span.mt-2 Quote #{quote.errors.messages[:text].join(', ')}!

app/views/quotes/partials/_pagy.html.haml
= turbo_frame_tag :pagy do
  .mt-2.flex.justify-center
    - if pagy.next.present?
      = pagy_next_link(pagy, text: 'More...', separate_route: true, link_extra: 'class="border rounded border-white border-2 p-1 hover:bg-white hover:text-black p-2" data-turbo-stream').html_safe

app/views/quotes/partials/_quote.html.haml
.mb-3.p-2.border.rounded.border-white.border-2{ id: "#{dom_id(quote)}_container"}
  = turbo_frame_tag quote, class: 'flex justify-between' do
    %p.flex-1.break-normal.pr-2= quote.text
    .flex.flex-col
      = link_to 'Details', quote_path(quote), data: { 'turbo-frame': :_top }, class: 'border rounded border-white border-2 p-1 hover:bg-white hover:text-black'
      .flex.items-center.mt-1
        = link_to 'Edit', edit_quote_path(quote), data: { 'turbo-frame': dom_id(quote) }, class: 'mr-1 border rounded border-white border-2 p-1 hover:bg-white hover:text-black'
        = link_to 'Delete', quote_path(quote), data: { 'turbo-frame': :quotes, 'turbo-method': :delete }, class: 'border rounded border-white border-2 p-1 hover:bg-white hover:text-black'

app/views/quotes/show.html.haml
%main.p-5.px-20
  .flex.flex-col.items-center
    %h1 Quote ##{@quote.id}
    .mt-5
      = @quote.text
    .flex.w-full.mt-5.justify-around
      %div Created at: #{@quote.created_at.strftime('%m/%d/%Y')}
      %div Updated at: #{@quote.updated_at.strftime('%m/%d/%Y')}
    .flex.mt-5.justify-around.w-32
      = link_to 'Edit', edit_quote_path(@quote), class: 'mr-1 border rounded border-white border-2 p-1 hover:bg-white hover:text-black'
      = link_to 'Delete', quote_path(id: @quote.id, from: :show), data: { 'turbo-frame': :_top, 'turbo-method': :delete }, class: 'border rounded border-white border-2 p-1 hover:bg-white hover:text-black'

app/views/quotes/update.turbo_stream.haml
= turbo_stream.replace "#{dom_id(@quote)}_container" do
  = render partial: 'quotes/partials/quote', locals: { quote: @quote }